{% set name = "code-server" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: https://github.com/cdr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: a5a5601c6e6e42f984c7dbb031e51c6be4bcbce54926bb41f22ef1ad8f522051
  - url: https://github.com/microsoft/vscode/archive/1.42.0.tar.gz
    sha256: b2d1cc61127483590fc47a0f8336605da0bbe92b3011024c77b2c15b13a23c8e
    folder: lib/vscode

build:
  number: 0
  binary_relocation: False  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 2.7.*
    - nodejs 12.14.*
    - yarn
  host:
    - nbin 1.2.7.*
    - libxkbfile  # [linux]
    - libsecret  # [linux]
    - xorg-libx11  # [linux]
  run:
    - nodejs 12.14.*
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
   - LICENSE.txt
   - lib/vscode/LICENSE.txt
   - lib/vscode/ThirdPartyNotices.txt
  summary: 'Run VS Code on a remote server.'

extra:
  recipe-maintainers:
    - xhochy
